name: test singleton status return

on:
  workflow_call:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test-singleton:
    name: Test singleton status return
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      
      - uses: actions/setup-go@v5
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - uses: ko-build/setup-ko@v0.6
      
      - name: Install dependencies
        run: |
          curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash
          wget https://github.com/kubestellar/kubeflex/releases/download/v0.4.1/kubeflex_0.4.1_linux_amd64.tar.gz
          tar -xvf kubeflex_0.4.1_linux_amd64.tar.gz bin/kflex
          mv bin/kflex /usr/local/bin
          rm -fr bin kubeflex_0.4.1_linux_amd64.tar.gz 

      - name: Run test
        run: |
          cd test/e2e/singleton-status
          KFLEX_DISABLE_CHATTY=true ./run-test.sh 

      - name: Investigate the kubestellar container
        if: always()
        run: |
          echo kubectl contexts:
          kubectl config get-contexts
          echo
          echo pods:
          kubectl --context kind-kubeflex get pods -A
          kpod=$(kubectl --context kind-kubeflex get pod -n wds1-system --selector=control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}')
          echo
          echo kubestellar controller log:
          kubectl --context kind-kubeflex logs -n wds1-system $kpod
          echo
          kubectl --context wds1 get placements -o yaml
          echo
          kubectl --context wds1 get placementdecisions -o yaml
          echo
          kubectl --context imbs1 get manifestworks -o yaml
          echo
          kubectl --context imbs1 get workstatuses -A -o yaml
